# s3 source URIs
src_URIs:
  - "s3://occupancy-dataset/occ-dataset/dairy/"

# s3 destination folder
dest_folder: "bev-dairy-more-navigable"

# json index path
index_json: "index-s3/dairy-more-navigable.json"

# color map config
color_map: "config/dairy.yaml"

# crop bounding box (x is horizontal, z is depth)
crop_bb:
  x_min: -2.0
  x_max: 3.0
  z_min: 2.0
  z_max: 7.0

# segmentation mask dimensions
nx: 256
nz: 256 