# default s3 uri to search for .svo files
dairy_folder_URI: "s3://sg-new-data/dairy_farm/"

farms_to_sample : [
    chino_valley, 
    coolidge, 
    escalon, 
    fiscalini, 
    ghdairy, 
    grimius, 
    mccarty, 
    mineral_king, 
    open_sky
    ]



svo_frames_to_sample: 20